---
title: "Visualizations - Thesis"
output: pdf_document
date: "2023-11-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos = c(CRAN = "https://cloud.r-project.org"))
```

```{r}
# Install and load the readxl package
install.packages("readxl")
library(readxl)
```

```{r}
setwd("/Users/katespencer")
excel_file_path <- "Desktop/eda_df.xlsx"
df <- read_excel(excel_file_path)
#names(df)
df$`Total Transaction Value ($USDmm, Historical rate)` <- as.numeric(df$`Total Transaction Value ($USDmm, Historical rate)`)
df$`Connected?` <- as.numeric(df$`Connected?`)
df$`Length of Transaction (Days)` <- as.numeric(df$`Length of Transaction (Days)`)
df$`Target Market Capitalization (1-Day Before Announcement) ($USDmm, Historical rate)` <- as.numeric(df$`Target Market Capitalization (1-Day Before Announcement) ($USDmm, Historical rate)`)
df$`net_debt` <- as.numeric(df$`net_debt`)
df$`EBITDA [LTM] ($USDmm, Historical rate) [Target/Issuer]` <- as.numeric(df$`EBITDA [LTM] ($USDmm, Historical rate) [Target/Issuer]`)
df$`Target/Issuer LTM Financials - EBIT (at Announcement) ($USDmm, Historical rate)` <- as.numeric(df$`Target/Issuer LTM Financials - EBIT (at Announcement) ($USDmm, Historical rate)`)
df$`Target/Issuer LTM Financials - Earnings from Continuing Ops (at Announcement) ($USDmm, Historical rate)` <- as.numeric(df$`Target/Issuer LTM Financials - Earnings from Continuing Ops (at Announcement) ($USDmm, Historical rate)`)
df$`Target/Issuer LTM Financials - Total Cash & ST Investments (at Announcement) ($USDmm, Historical rate)` <- as.numeric(df$`Target/Issuer LTM Financials - Total Cash & ST Investments (at Announcement) ($USDmm, Historical rate)`)
df$`Target/Issuer LTM Financials - Total Assets (at Announcement) ($USDmm, Historical rate)` <- as.numeric(df$`Target/Issuer LTM Financials - Total Assets (at Announcement) ($USDmm, Historical rate)`)
```
```{r}
install.packages("stargazer")
library(stargazer)

# Load the pander library if not already installed
if (!requireNamespace("pander", quietly = TRUE)) {
  install.packages("pander")
}
library(pander)
install.packages("knitr")
library(knitr)

```

```{r}
c <- df[df$`Connected?` == 1, ]
nc <- df[df$`Connected?` == 0, ]
mean_size_connected <- mean(c$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
mean_size_notconnected <- mean(nc$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)

#Significant
values_connected <- c$`Total Transaction Value ($USDmm, Historical rate)`
values_notconnected <- nc$`Total Transaction Value ($USDmm, Historical rate)`
t_test_result_size <- t.test(values_connected, values_notconnected, na.rm = TRUE)
p_value_s <- t_test_result_size$p.value

mean_length_connected <- mean(c$`Length of Transaction (Days)`, na.rm = TRUE)
mean_length_notconnected <- mean(nc$`Length of Transaction (Days)`, na.rm = TRUE)

#Significant
t_test_result_length <- t.test(c$`Length of Transaction (Days)`, nc$`Length of Transaction (Days)`, na.rm = TRUE)
p_value_l <- t_test_result_length$p.value

x <- data.frame(
  "_" = c("Average Length of Transaction, Days", "Average Transaction Size, $Ms USD"),
  "Connected (n=664)" = c(mean_length_connected, mean_size_connected),
  "Not Connected (n=972)" = c(mean_length_notconnected, mean_size_notconnected),
  "p-Value of Difference" = c(p_value_l, p_value_s)
)

kable(x, format = "latex") 
```

```{r}
# Annual Analysis
# All mean differences are significant between connected and not connected firms, except for 2019 
c18<-c[c$`Year` == 2018, ]
c19<-c[c$`Year` == 2019, ]
c20<-c[c$`Year` == 2020, ]
c21<-c[c$`Year` == 2021, ]
c22<-c[c$`Year` == 2022, ]

nc18<-nc[nc$`Year` == 2018, ]
nc19<-nc[nc$`Year` == 2019, ]
nc20<-nc[nc$`Year` == 2020, ]
nc21<-nc[nc$`Year` == 2021, ]
nc22<-nc[nc$`Year` == 2022, ]

msc18 <- mean(c18$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msc19 <- mean(c19$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msc20 <- mean(c20$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msc21 <- mean(c21$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msc22 <- mean(c22$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)

msnc18 <- mean(nc18$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msnc19 <- mean(nc19$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msnc20 <- mean(nc20$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msnc21 <- mean(nc21$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msnc22 <- mean(nc22$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)

tt18 <- t.test(c18$`Total Transaction Value ($USDmm, Historical rate)`, nc18$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
tt19 <- t.test(c19$`Total Transaction Value ($USDmm, Historical rate)`, nc19$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
tt20 <- t.test(c20$`Total Transaction Value ($USDmm, Historical rate)`, nc20$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
tt21 <- t.test(c21$`Total Transaction Value ($USDmm, Historical rate)`, nc21$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
tt22 <- t.test(c22$`Total Transaction Value ($USDmm, Historical rate)`, nc22$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)

p18 <- tt18$p.value
p19 <- tt19$p.value
p20 <- tt20$p.value
p21 <- tt21$p.value
p22 <- tt22$p.value

print(p18)
print(p19)
print(p20)
print(p21)
print(p21)

print(msc18-msnc18)
print(msc19-msnc19)
print(msc20-msnc20)
print(msc21-msnc21)
print(msc22-msnc22)
````

```{r}
# Annual Analysis
# None of the length differences are signfiicant annually

mlc18 <- mean(c18$`Length of Transaction (Days)`, na.rm = TRUE)
mlc19 <- mean(c19$`Length of Transaction (Days)`, na.rm = TRUE)
mlc20 <- mean(c20$`Length of Transaction (Days)`, na.rm = TRUE)
mlc21 <- mean(c21$`Length of Transaction (Days)`, na.rm = TRUE)
mlc22 <- mean(c22$`Length of Transaction (Days)`, na.rm = TRUE)

mlnc18 <- mean(nc18$`Length of Transaction (Days)`, na.rm = TRUE)
mlnc19 <- mean(nc19$`Length of Transaction (Days)`, na.rm = TRUE)
mlnc20 <- mean(nc20$`Length of Transaction (Days)`, na.rm = TRUE)
mlnc21 <- mean(nc21$`Length of Transaction (Days)`, na.rm = TRUE)
mlnc22 <- mean(nc22$`Length of Transaction (Days)`, na.rm = TRUE)

tt18l <- t.test(c18$`Length of Transaction (Days)`, nc18$`Length of Transaction (Days)`, na.rm = TRUE)
tt19l <- t.test(c19$`Length of Transaction (Days)`, nc19$`Length of Transaction (Days)`, na.rm = TRUE)
tt20l <- t.test(c20$`Length of Transaction (Days)`, nc20$`Length of Transaction (Days)`, na.rm = TRUE)
tt21l <- t.test(c21$`Length of Transaction (Days)`, nc21$`Length of Transaction (Days)`, na.rm = TRUE)
tt22l <- t.test(c22$`Length of Transaction (Days)`, nc22$`Length of Transaction (Days)`, na.rm = TRUE)

p18l <- tt18l$p.value
p19l <- tt19l$p.value
p20l <- tt20l$p.value
p21l <- tt21l$p.value
p22l <- tt22l$p.value

print(p18l)
print(p19l)
print(p20l)
print(p21l)
print(p21l)

print(mlc18-mlnc18)
print(mlc19-mlnc19)
print(mlc20-mlnc20)
print(mlc21-mlnc21)
print(mlc22-mlnc22)
````

```{r}
# Financial Analysis
# Connected firms exit high market cap companies with more cash on balance sheet at time of transaction

cmarketcap <- mean(c$`Target Market Capitalization (1-Day Before Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
ncmarketcap <- mean(nc$`Target Market Capitalization (1-Day Before Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
cnetdebt <- mean(c$`net_debt`, na.rm = TRUE)
ncnetdebt <- mean(nc$`net_debt`, na.rm = TRUE)
cebitda <- mean(c$`EBITDA [LTM] ($USDmm, Historical rate) [Target/Issuer]`, na.rm = TRUE)
ncebitda <- mean(nc$`EBITDA [LTM] ($USDmm, Historical rate) [Target/Issuer]`, na.rm = TRUE)
cebit <- mean(c$`Target/Issuer LTM Financials - EBIT (at Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
ncebit <- mean(nc$`Target/Issuer LTM Financials - EBIT (at Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
ccont <- mean(c$`Target/Issuer LTM Financials - Earnings from Continuing Ops (at Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
nccont <- mean(nc$`Target/Issuer LTM Financials - Earnings from Continuing Ops (at Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
ccash <- mean(c$`Target/Issuer LTM Financials - Total Cash & ST Investments (at Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
ncash <- mean(nc$`Target/Issuer LTM Financials - Total Cash & ST Investments (at Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
cassets <- mean(c$`Target/Issuer LTM Financials - Total Assets (at Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
ncassets <- mean(nc$`Target/Issuer LTM Financials - Total Assets (at Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
cpremium <- mean(c$`premium_paid`, na.rm = TRUE)
ncpremium <- mean(nc$`premium_paid`, na.rm = TRUE)

ttmarketcap <- t.test(c$`Target Market Capitalization (1-Day Before Announcement) ($USDmm, Historical rate)`, nc$`Target Market Capitalization (1-Day Before Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
ttnetdebt <- t.test(c$`net_debt`, nc$`net_debt`, na.rm = TRUE)
ttebitda <- t.test(c$`EBITDA [LTM] ($USDmm, Historical rate) [Target/Issuer]`, nc$`EBITDA [LTM] ($USDmm, Historical rate) [Target/Issuer]`, na.rm = TRUE)
ttebit <- t.test(c$`Target/Issuer LTM Financials - EBIT (at Announcement) ($USDmm, Historical rate)`, nc$`Target/Issuer LTM Financials - EBIT (at Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
ttcont <- t.test(c$`Target/Issuer LTM Financials - Earnings from Continuing Ops (at Announcement) ($USDmm, Historical rate)`, nc$`Target/Issuer LTM Financials - Earnings from Continuing Ops (at Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
ttcash <- t.test(c$`Target/Issuer LTM Financials - Total Cash & ST Investments (at Announcement) ($USDmm, Historical rate)`, nc$`Target/Issuer LTM Financials - Total Cash & ST Investments (at Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
ttassets <- t.test(c$`Target/Issuer LTM Financials - Total Assets (at Announcement) ($USDmm, Historical rate)`, nc$`Target/Issuer LTM Financials - Total Assets (at Announcement) ($USDmm, Historical rate)`, na.rm = TRUE)
ttpremium <- t.test(c$`premium_paid`, nc$`premium_paid`,na.rm = TRUE)

pmarketcap <- ttmarketcap$p.value
pnetdebt <- ttnetdebt$p.value
pebitda <- ttebitda$p.value
pebit <- ttebit$p.value
pcont <- ttcont$p.value
pcash <- ttcash$p.value
passets <- ttassets$p.value
ppremium <- ttpremium$p.value

print(pmarketcap) #sig
print(pnetdebt) #almost sig 
print(pebitda)
print(pebit)
print(pcont)
print(pcash) #sig
print(passets)
print(ppremium)


print(cmarketcap-ncmarketcap)
print(ccash-ncash)
```

```{r}
#Industry analysis
# Signifcant for the financial industry 
cretail<-c[c$`Industry_Group` == 'Consumer Goods and Retail', ]
ceducation<-c[c$`Industry_Group` == 'Education', ]
cenergy<-c[c$`Industry_Group` == 'Energy', ]
cfin<-c[c$`Industry_Group` == 'Financial Services', ]
chealth<-c[c$`Industry_Group` == 'Healthcare and Life Sciences', ]
cmanu<-c[c$`Industry_Group` == 'Manufacturing and Industrial', ]
ctech<-c[c$`Industry_Group` == 'Technology and Communications', ]
ctrans<-c[c$`Industry_Group` == 'Transportation and Logistics', ]
cutil<-c[c$`Industry_Group` == 'Utilities and Services', ]

ncretail<-nc[nc$`Industry_Group` == 'Consumer Goods and Retail', ]
nceducation<-nc[nc$`Industry_Group` == 'Education', ]
ncenergy<-nc[nc$`Industry_Group` == 'Energy', ]
ncfin<-nc[nc$`Industry_Group` == 'Financial Services', ]
nchealth<-nc[nc$`Industry_Group` == 'Healthcare and Life Sciences', ]
ncmanu<-nc[nc$`Industry_Group` == 'Manufacturing and Industrial', ]
nctech<-nc[nc$`Industry_Group` == 'Technology and Communications', ]
nctrans<-nc[nc$`Industry_Group` == 'Transportation and Logistics', ]
ncutil<-nc[nc$`Industry_Group` == 'Utilities and Services', ]

mlcr <- mean(cretail$`Length of Transaction (Days)`, na.rm = TRUE)
mlce <- mean(ceducation$`Length of Transaction (Days)`, na.rm = TRUE)
mlcen <- mean(cenergy$`Length of Transaction (Days)`, na.rm = TRUE)
mlcf <- mean(cfin$`Length of Transaction (Days)`, na.rm = TRUE)
mlch <- mean(chealth$`Length of Transaction (Days)`, na.rm = TRUE)
mlcm <- mean(cmanu$`Length of Transaction (Days)`, na.rm = TRUE)
mlct <- mean(ctech$`Length of Transaction (Days)`, na.rm = TRUE)
mlctr <- mean(ctrans$`Length of Transaction (Days)`, na.rm = TRUE)
mlcu <- mean(cutil$`Length of Transaction (Days)`, na.rm = TRUE)

mlncr <- mean(ncretail$`Length of Transaction (Days)`, na.rm = TRUE)
mlnce <- mean(nceducation$`Length of Transaction (Days)`, na.rm = TRUE)
mlncen <- mean(ncenergy$`Length of Transaction (Days)`, na.rm = TRUE)
mlncf <- mean(ncfin$`Length of Transaction (Days)`, na.rm = TRUE)
mlnch <- mean(nchealth$`Length of Transaction (Days)`, na.rm = TRUE)
mlncm <- mean(ncmanu$`Length of Transaction (Days)`, na.rm = TRUE)
mlnct <- mean(nctech$`Length of Transaction (Days)`, na.rm = TRUE)
mlnctr <- mean(nctrans$`Length of Transaction (Days)`, na.rm = TRUE)
mlncu <- mean(ncutil$`Length of Transaction (Days)`, na.rm = TRUE)

ttretail <- t.test(cretail$`Length of Transaction (Days)`, ncretail$`Length of Transaction (Days)`, na.rm = TRUE)
tteducation <- t.test(ceducation$`Length of Transaction (Days)`, nceducation$`Length of Transaction (Days)`, na.rm = TRUE)
ttenergy <- t.test(cenergy$`Length of Transaction (Days)`, ncenergy$`Length of Transaction (Days)`, na.rm = TRUE)
ttfin <- t.test(cfin$`Length of Transaction (Days)`, ncfin$`Length of Transaction (Days)`, na.rm = TRUE)
tthealth <- t.test(chealth$`Length of Transaction (Days)`, nchealth$`Length of Transaction (Days)`, na.rm = TRUE)
ttmanu <- t.test(cmanu$`Length of Transaction (Days)`, ncmanu$`Length of Transaction (Days)`, na.rm = TRUE)
tttech <- t.test(ctech$`Length of Transaction (Days)`, nctech$`Length of Transaction (Days)`, na.rm = TRUE)
tttrans <- t.test(ctrans$`Length of Transaction (Days)`, nctrans$`Length of Transaction (Days)`, na.rm = TRUE)
ttutil <- t.test(cutil$`Length of Transaction (Days)`, ncutil$`Length of Transaction (Days)`, na.rm = TRUE)

pretail <- ttretail$p.value
peducation <- tteducation$p.value
penergy <- ttenergy$p.value
pfin <- ttfin$p.value
phealth <- tthealth$p.value
pmanu <- ttmanu$p.value
ptech <- tttech$p.value
ptrans <- tttrans$p.value
putil <- ttutil$p.value

print(pretail) 
print(peducation) 
print(penergy)
print(pfin) # almost sig
print(phealth)
print(pmanu) 
print(ptech)
print(ptrans)
print(putil)


```

```{r}
#Size of transaction, industry 
mscr <- mean(cretail$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msce <- mean(ceducation$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
mscen <- mean(cenergy$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
mscf <- mean(cfin$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msch <- mean(chealth$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
mscm <- mean(cmanu$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msct <- mean(ctech$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msctr <- mean(ctrans$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
mscu <- mean(cutil$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)

msncr <- mean(ncretail$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msnce <- mean(nceducation$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msncen <- mean(ncenergy$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msncf <- mean(ncfin$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msnch <- mean(nchealth$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msncm <- mean(ncmanu$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msnct <- mean(nctech$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msnctr <- mean(nctrans$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
msncu <- mean(ncutil$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)

ttretails <- t.test(cretail$`Total Transaction Value ($USDmm, Historical rate)`, ncretail$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
tteducations <- t.test(ceducation$`Total Transaction Value ($USDmm, Historical rate)`, nceducation$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
ttenergys <- t.test(cenergy$`Total Transaction Value ($USDmm, Historical rate)`, ncenergy$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
ttfins <- t.test(cfin$`Total Transaction Value ($USDmm, Historical rate)`, ncfin$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
tthealths <- t.test(chealth$`Total Transaction Value ($USDmm, Historical rate)`, nchealth$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
ttmanus <- t.test(cmanu$`Total Transaction Value ($USDmm, Historical rate)`, ncmanu$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
tttechs <- t.test(ctech$`Total Transaction Value ($USDmm, Historical rate)`, nctech$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
tttranss <- t.test(ctrans$`Total Transaction Value ($USDmm, Historical rate)`, nctrans$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)
ttutils <- t.test(cutil$`Total Transaction Value ($USDmm, Historical rate)`, ncutil$`Total Transaction Value ($USDmm, Historical rate)`, na.rm = TRUE)

pretails <- ttretails$p.value
peducations <- tteducations$p.value
penergys <- ttenergys$p.value
pfins <- ttfins$p.value
phealths <- tthealths$p.value
pmanus <- ttmanus$p.value
ptechs <- tttechs$p.value
ptranss <- tttranss$p.value
putils <- ttutils$p.value

print(pretails) 
print(peducations) 
print(penergys) #sig
print(pfins) 
print(phealths) #sig
print(pmanus) #sig
print(ptechs) #sig
print(ptranss)
print(putils)
```
